export const labels = {
  common: {
    create: 'Crear',
    edit: 'Editar',
    save: 'Guardar',
    cancel: 'Cancelar',
    loading: 'Cargando...',
    success: 'Operación exitosa',
    error: 'Ocurrió un error inesperado',
    search: 'Buscar...',
    noResults: 'Sin resultados',
    name: 'Nombre',
    delete: 'Eliminar',
    actions: 'Acciones',
    view: 'Ver',
    manage: 'Administrar',
    status: 'Estado',
    createdAt: 'Fecha de creación',
    active: 'Activo',
    inactive: 'Inactivo',
    blocked: 'Bloqueado',
    confirm: 'Confirmar',
    back: 'Volver',
    filters: 'Filtros',
    appName: 'Skeleton',
    selected: 'Seleccionado',
    drawer: {
      close: 'Cerrar',
    },
  },
  nav: {
    general: 'General',
    dashboard: 'Dashboard',
    operations: 'Operaciones',
    projects: 'Proyectos',
    dispatch: 'Despacho',
    returns: 'Devoluciones',
    samples: 'Muestras',
    warehouse: 'Almacén',
    reception: 'Recepción / OC',
    inventory: 'Inventario',
    production: 'Producción',
    finance: 'Finanzas',
    billing: 'Facturación',
    contpaqi: 'CONTAQi',
    accountsReceivable: 'CxC',
    accountsPayable: 'CxP',
    administration: 'Administración',
    users: 'Usuarios',
    roles: 'Roles',
    dataScopes: 'Alcance de datos',
    security: 'Seguridad',
    humanResources: 'Recursos Humanos',
    rrhh: 'RRHH',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Vista de',
    stats: {
      activeProjects: 'Proyectos Activos',
      activeProjectsSub: '+2 este mes',
      pendingOrders: 'Ordenes Pendientes',
      pendingOrdersSub: '3 urgentes',
      monthlyBilling: 'Facturación del Mes',
      monthlyBillingSub: '+15% vs anterior',
      activeEmployees: 'Empleados Activos',
      activeEmployeesSub: '2 nuevos ingresos',
    },
    alerts: {
      title: 'Alertas Recientes',
      purchaseOrdersDue: '3 órdenes de compra vencen mañana',
      lowStock: 'Stock bajo en Solvente A-100 (Tanque 3)',
      productionComplete: 'Producción lote #2847 completada',
      invoicePending: 'Factura FE-2024-0891 pendiente de pago',
      ago2h: 'Hace 2h',
      ago4h: 'Hace 4h',
      ago6h: 'Hace 6h',
      ago1d: 'Hace 1d',
    },
    quickActions: {
      title: 'Accesos Rápidos',
      newPurchaseOrder: 'Nueva Orden de Compra',
      registerDispatch: 'Registrar Despacho',
      createInvoice: 'Crear Factura',
      assignTask: 'Asignar Tarea',
    },
  },
  auth: {
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    email: 'Correo electrónico',
    password: 'Contraseña',
    rememberMe: 'Recordar este dispositivo',
    forgotPassword: '¿Olvidó su contraseña?',
    loginSubtitle: 'Bienvenido de nuevo. Ingrese sus credenciales para continuar.',
    emailPlaceholder: 'usuario@empresa.com',
    forgotPasswordSubtitle: 'Ingrese su correo electrónico y le enviaremos un enlace para restablecer su contraseña.',
    resetPassword: 'Restablecer contraseña',
    resetPasswordSubtitle: 'Ingrese su nueva contraseña para completar el restablecimiento.',
    sendResetLink: 'Enviar enlace de restablecimiento',
    backToLogin: 'Volver a iniciar sesión',
    newPassword: 'Nueva contraseña',
    confirmPassword: 'Confirmar contraseña',
    currentPassword: 'Contraseña actual',
    changePassword: 'Cambiar contraseña',
    resetSent: 'Se ha enviado el enlace de restablecimiento a tu correo.',
    resetSuccess: 'Tu contraseña ha sido restablecida.',
    loginFailed: 'Credenciales inválidas.',
    passwordChanged: 'Contraseña actualizada exitosamente.',
  },
  branding: {
    appName: 'Mitra ERP',
    headline: 'Gestión integral para tu industria',
    tagline: 'Potencia la eficiencia de tu operación con nuestra plataforma de arquitectura empresarial.',
    featureAccess: 'Control de acceso avanzado',
    featureTraceability: 'Trazabilidad de procesos',
    featureAudit: 'Auditoría y cumplimiento',
    copyright: '© 2024 Architectural ERP Systems. Todos los derechos reservados.',
    version: 'Versión 4.2.0-stable',
    privacy: 'Privacidad',
    support: 'Soporte técnico',
  },
  users: {
    title: 'Usuarios',
    titleFull: 'Usuarios y RBAC',
    invite: 'Agregar',
    create: 'Crear usuario',
    created: 'Usuario creado exitosamente.',
    updated: 'Usuario actualizado exitosamente.',
    empty: 'No hay usuarios registrados.',
    searchPlaceholder: 'Buscar por nombre o email...',
    noRoles: 'Sin roles',
    resultCount: (count: number) => `${count} usuario(s)`,
    phone: 'Teléfono',
    lastLogin: 'Último acceso',
    avatar: {
      label: 'Foto de perfil',
      upload: 'Subir foto',
      replace: 'Cambiar foto',
      delete: 'Eliminar foto',
      deleted: 'Foto eliminada',
      uploaded: 'Foto actualizada',
      uploadError: 'Error al subir la foto',
      deleteError: 'Error al eliminar la foto',
      formats: 'JPG, PNG o WebP. Máx 2MB.',
    },
    roles: 'Roles',
    permissions: 'Permisos',
    forcePassword: 'Forzar cambio de contraseña',
    passwordForced: 'Contraseña del usuario actualizada.',
    avatarUploaded: 'Foto de perfil actualizada.',
    rolesUpdated: 'Roles del usuario actualizados.',
    fields: {
      name: 'Nombre',
      email: 'Correo electrónico',
      phone: 'Teléfono',
      status: 'Estado',
      password: 'Contraseña',
      passwordConfirmation: 'Confirmar contraseña',
    },
    statuses: {
      active: 'Activo',
      inactive: 'Inactivo',
      blocked: 'Bloqueado',
    },
    filters: {
      allRoles: 'Todos los roles',
      role: 'Filtrar por rol',
      status: 'Filtrar por estado',
      dateFrom: 'Desde',
      dateTo: 'Hasta',
    },
    sections: {
      info: 'Información',
      roles: 'Roles',
      access: 'Acceso',
    },
  },
  roles: {
    title: 'Roles',
    create: 'Crear rol',
    invite: 'Agregar',
    created: 'Rol creado exitosamente.',
    updated: 'Rol actualizado.',
    deleted: 'Rol eliminado.',
    duplicated: 'Rol duplicado exitosamente.',
    empty: 'No hay roles configurados.',
    searchPlaceholder: 'Buscar por nombre...',
    resultCount: (count: number) => `${count} rol(es)`,
    duplicate: 'Duplicar',
    duplicateName: 'Nombre del nuevo rol',
    systemProtected: 'Rol de sistema (protegido)',
    permissionsSynced: 'Permisos actualizados.',
    fields: {
      name: 'Nombre',
      description: 'Descripción',
      usersCount: 'Usuarios',
      permissionsCount: 'Permisos',
    },
    sections: {
      info: 'Información',
    },
  },
  permissions: {
    title: 'Permisos',
    matrix: 'Matriz de permisos',
    effective: 'Acceso efectivo',
    source: {
      role: 'Heredado de rol',
      directGrant: 'Otorgado directamente',
      directDeny: 'Denegado explícitamente',
    },
    grant: 'Otorgar',
    deny: 'Denegar',
    none: 'Sin asignar',
    synced: 'Permisos directos actualizados.',
  },
  dataScopes: {
    title: 'Alcance de datos',
    create: 'Crear regla de alcance',
    invite: 'Agregar',
    created: 'Regla de alcance creada.',
    updated: 'Regla de alcance actualizada.',
    deleted: 'Regla de alcance eliminada.',
    empty: 'No hay reglas de alcance configuradas.',
    searchPlaceholder: 'Buscar por nombre...',
    resultCount: (count: number) => `${count} regla(s)`,
    allEntities: 'Todas las entidades',
    preview: 'Vista previa',
    previewResults: 'registros coinciden con esta regla',
    selectEntity: 'Seleccionar entidad',
    selectType: 'Seleccionar tipo de regla',
    rulesSynced: 'Reglas de alcance actualizadas.',
    fields: {
      name: 'Nombre',
      entity: 'Entidad',
      type: 'Tipo de regla',
      description: 'Descripción',
      configuration: 'Configuración',
    },
    types: {
      own: 'Solo registros propios',
      relation: 'Por relación',
      field_value: 'Por valor de campo',
      all: 'Acceso total',
      custom: 'Regla personalizada',
    },
    typeDescriptions: {
      own: 'El usuario solo ve los registros que creó.',
      relation: 'El usuario ve registros vinculados a él a través de otra entidad.',
      field_value: 'El usuario ve registros que cumplen una condición sobre un campo.',
      all: 'Sin restricción — el usuario ve todos los registros.',
      custom: 'Condición avanzada definida por código.',
    },
    configLabels: {
      ownerColumn: 'Columna del propietario',
      pivotTable: 'Tabla pivote',
      entityForeignKey: 'Clave foránea de la entidad',
      userForeignKey: 'Clave foránea del usuario',
      column: 'Columna',
      operator: 'Operador',
      value: 'Valor',
      scopeClass: 'Clase del scope',
    },
    sections: {
      rule: 'Regla',
      configuration: 'Configuración',
      info: 'Información',
    },
  },
  rrhh: {
    title: 'Recursos Humanos',
    subtitle: 'Organigrama, empleados, puestos, áreas y documentación',
    stats: {
      activeEmployees: 'Empleados Activos',
      blockedEmployees: 'Empleados Bloqueados',
      completeDocs: 'Expedientes Completos',
      incompleteDocs: 'Expedientes Pendientes',
      activePositions: 'Puestos Activos',
    },
    tabs: {
      orgChart: 'Organigrama',
      employees: 'Empleados',
      positions: 'Puestos',
      areas: 'Áreas',
      documentation: 'Documentación',
      reports: 'Reportes',
      comingSoon: 'Próximamente',
    },
    areas: {
      title: 'Áreas',
      create: 'Nueva Área',
      created: 'Área creada exitosamente',
      updated: 'Área actualizada exitosamente',
      empty: 'No hay áreas registradas',
      fields: {
        name: 'Nombre',
        status: 'Estado',
      },
    },
    positions: {
      title: 'Puestos',
      create: 'Nuevo Puesto',
      created: 'Puesto creado exitosamente',
      updated: 'Puesto actualizado exitosamente',
      empty: 'No hay puestos registrados',
      selectArea: 'Seleccionar área',
      noReportsTo: 'Ninguno (puesto raíz)',
      fields: {
        name: 'Nombre',
        area: 'Área',
        authorizedPositions: 'Plazas autorizadas',
        reportsTo: 'Reporta a',
        status: 'Estado',
        documents: 'Documentos',
      },
      documentsSection: {
        title: 'Documentos aplicables',
        required: 'Requerido',
        optional: 'Opcional',
        noDocuments: 'No hay documentos configurados',
      },
    },
    documents: {
      title: 'Documentación',
      create: 'Nuevo Documento',
      created: 'Documento creado exitosamente',
      updated: 'Documento actualizado exitosamente',
      empty: 'No hay documentos registrados',
      fields: {
        name: 'Nombre',
        description: 'Descripción',
        isRequiredByDefault: 'Requerido por defecto',
        status: 'Estado',
        positionsCount: 'Puestos asignados',
      },
    },
    employees: {
      title: 'Empleados',
      create: 'Nuevo Empleado',
      created: 'Empleado creado exitosamente',
      updated: 'Empleado actualizado exitosamente',
      empty: 'No hay empleados registrados',
      blocked: 'Empleado bloqueado',
      unblocked: 'Empleado desbloqueado',
      selectPosition: 'Seleccionar puesto',
      generatePassword: 'Generar contraseña',
      blockAction: 'Bloquear',
      unblockAction: 'Desbloquear',
      fields: {
        name: 'Nombre',
        email: 'Correo electrónico',
        password: 'Contraseña',
        passwordConfirmation: 'Confirmar contraseña',
        position: 'Puesto',
        area: 'Área',
        hiredAt: 'Fecha de ingreso',
        seniority: 'Antigüedad',
        location: 'Ubicación',
        status: 'Estado',
        documents: 'Documentos',
      },
      statuses: {
        active: 'Activo',
        blocked: 'Bloqueado',
      },
      docs: {
        complete: 'Completo',
        incomplete: 'Incompleto',
        required: 'Requerido',
        optional: 'Opcional',
        uploaded: 'Cargado',
        pending: 'Pendiente',
        upload: 'Cargar documento',
        replace: 'Reemplazar',
        compliance: 'Cumplimiento documental',
        noDocuments: 'Sin documentos configurados',
        temporaryPassword: 'Contraseña temporal',
        temporaryPasswordMessage: 'La contraseña temporal del empleado es:',
        requiredSummary: (uploaded: number, total: number) => `${uploaded}/${total} requeridos`,
        optionalSummary: (uploaded: number, total: number) => `${uploaded}/${total} opcionales`,
        manageDocs: 'Gestionar documentos',
      },
      seniorityYears: 'años',
      sections: {
        info: 'Información General',
      },
    },
    orgChart: {
      title: 'Organigrama',
      empty: 'No hay puestos activos para mostrar',
      filterByArea: 'Filtrar por área',
      allAreas: 'Todas las áreas',
      employeeStatus: 'Estado de empleados',
      statusAll: 'Todos',
      statusActive: 'Activos',
      statusBlocked: 'Bloqueados',
      vacancies: (count: number) => `${count} vacante${count !== 1 ? 's' : ''}`,
      moreEmployees: (count: number) => `+${count}`,
      nodeDetail: 'Detalle del puesto',
      positionInfo: 'Información del puesto',
      employeeList: 'Empleados asignados',
      noEmployees: 'Sin empleados asignados',
      viewEmployee: 'Ver detalle',
      expand: 'Expandir',
      collapse: 'Colapsar',
    },
    reports: {
      title: 'Reportes',
      empty: 'No hay datos disponibles con los filtros seleccionados',
      filters: {
        area: 'Área',
        allAreas: 'Todas las áreas',
        employeeStatus: 'Estado de empleado',
        statusAll: 'Todos',
        statusActive: 'Activos',
        statusBlocked: 'Bloqueados',
        docStatus: 'Estado documental',
        docAll: 'Todos',
        docComplete: 'Completo',
        docPending: 'Pendiente',
        docNoRequirements: 'Sin requisitos',
        seniorityMin: 'Antigüedad mín. (años)',
        seniorityMax: 'Antigüedad máx. (años)',
      },
      charts: {
        areaDistribution: 'Distribución por Área',
        positionOccupancy: 'Ocupación por Puesto',
        docCompliance: 'Cumplimiento Documental',
        occupied: 'Ocupados',
        authorized: 'Autorizados',
        employees: 'Empleados',
        complete: 'Completo',
        pending: 'Pendiente',
        noRequirements: 'Sin requisitos',
      },
      pending: {
        title: 'Empleados con Documentos Pendientes',
        empty: 'No hay empleados con documentos pendientes',
        missingDocs: (count: number) => `${count} documento${count !== 1 ? 's' : ''} faltante${count !== 1 ? 's' : ''}`,
      },
      table: {
        title: 'Resumen de Empleados',
        columns: {
          name: 'Nombre',
          position: 'Puesto',
          area: 'Área',
          seniority: 'Antigüedad',
          docStatus: 'Estado Documental',
          status: 'Estado',
        },
        years: 'años',
      },
    },
    statuses: {
      active: 'Activo',
      inactive: 'Inactivo',
      blocked: 'Bloqueado',
    },
  },
  table: {
    page: 'Página',
    of: 'de',
    perPage: 'por página',
    results: (count: number) => `${count} resultado${count !== 1 ? 's' : ''}`,
    previous: 'Anterior',
    next: 'Siguiente',
    noResults: 'Sin resultados.',
    filterPlaceholder: 'Filtrar...',
    clearFilters: 'Limpiar filtros',
    allItems: 'Todos',
  },
} as const
